'use client';

import { useState, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import useSWR from 'swr';
import { PageHeader } from '@/components/layout/PageHeader';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { tabdealApi, ApiError } from '@/lib/api';
import { Building, ShieldCheck, HelpCircle, Copy, Check, Eye, EyeOff, AlertTriangle } from 'lucide-react';
import toast from 'react-hot-toast';

export default function CreateClientPage() {
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [successData, setSuccessData] = useState<any | null>(null);

  const [formData, setFormData] = useState({
    businessName: '',
    categoryId: '',
    email: '',
    whatsappNumber: '',
    website: '',
  });

  const { data: categoriesData, isLoading: loadingCategories } = useSWR(
    '/api/tabdeal/categories',
    tabdealApi.getCategories
  );

  const autoGeneratedSlug = useMemo(() => {
    return formData.businessName
      ? formData.businessName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
      : 'auto-generated-slug';
  }, [formData.businessName]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);

    if (!formData.businessName.trim() || !formData.categoryId) {
      setFormError('Business name and category are required.');
      return;
    }

    setIsSubmitting(true);
    try {
      const res = await tabdealApi.createClient({
        businessName: formData.businessName,
        categoryId: formData.categoryId,
        email: formData.email || undefined,
        whatsappNumber: formData.whatsappNumber || undefined,
        website: formData.website || undefined,
      });

      // Instead of redirecting, show the credential handover state
      toast.success('Client created successfully');
      setSuccessData(res.data);
    } catch (err: any) {
      if (err instanceof ApiError) {
        setFormError(err.message || 'Failed to create client');
      } else {
        setFormError('An unexpected server error occurred.');
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  const categories = categoriesData?.data?.filter((c: any) => c.active) || [];

  if (successData) {
    return <CredentialHandover successData={successData} setSuccessData={setSuccessData} />;
  }

  return (
    <div className="max-w-4xl mx-auto animate-in fade-in duration-500 space-y-6">
      <PageHeader 
        title="Create Client" 
        description="Provision a new isolated client tenant. The system will automatically provision their templates and WhatsApp instance." 
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2">
          <Card className="p-6">
            <form onSubmit={handleSubmit} className="space-y-6">
              
              {formError && (
                <div className="p-4 bg-rose-50 border border-rose-200 rounded-lg flex items-start gap-3 text-rose-800">
                  <HelpCircle className="w-5 h-5 shrink-0 mt-0.5" />
                  <span className="text-sm font-medium">{formError}</span>
                </div>
              )}

              <div className="space-y-4">
                <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider border-b border-gray-100 pb-2">
                  Business Information
                </h3>
                
                <div>
                  <Input
                    label="Business Name"
                    placeholder="e.g. Divine Tours"
                    value={formData.businessName}
                    onChange={(e) => setFormData(f => ({ ...f, businessName: e.target.value }))}
                    required
                    maxLength={150}
                  />
                  <p className="text-xs text-gray-500 mt-1.5">The official name of the client.</p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Business Category
                  </label>
                  <select
                    className="block w-full rounded-lg border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white py-2.5 px-3"
                    value={formData.categoryId}
                    onChange={(e) => setFormData(f => ({ ...f, categoryId: e.target.value }))}
                    required
                    disabled={loadingCategories}
                  >
                    <option value="" disabled>Select a category...</option>
                    {categories.map((c: any) => (
                      <option key={c._id} value={c._id}>
                        {c.name} {c.defaultTemplatePackId ? '' : '(No default template pack)'}
                      </option>
                    ))}
                  </select>
                  {loadingCategories ? (
                    <p className="text-xs text-gray-500 mt-1.5 animate-pulse">Loading active categories...</p>
                  ) : (
                    <p className="text-xs text-gray-500 mt-1.5">
                      Determines the default master templates provisioned for this client.
                    </p>
                  )}
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
                  <Input
                    label="Contact Email (Optional)"
                    type="email"
                    placeholder="contact@business.com"
                    value={formData.email}
                    onChange={(e) => setFormData(f => ({ ...f, email: e.target.value }))}
                  />
                  
                  <div>
                    <Input
                      label="WhatsApp Number (Optional)"
                      placeholder="e.g. 919876543210"
                      value={formData.whatsappNumber}
                      onChange={(e) => setFormData(f => ({ ...f, whatsappNumber: e.target.value }))}
                    />
                    <p className="text-xs text-gray-500 mt-1.5">Include country code without plus sign.</p>
                  </div>
                </div>

                <div>
                  <Input
                    label="Website (Optional)"
                    type="url"
                    placeholder="https://business.com"
                    value={formData.website}
                    onChange={(e) => setFormData(f => ({ ...f, website: e.target.value }))}
                  />
                </div>
              </div>

              <div className="space-y-4 pt-4">
                <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider border-b border-gray-100 pb-2 flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-indigo-500" /> System Identity (Auto-Generated)
                </h3>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <Input
                      label="Client Slug"
                      value={autoGeneratedSlug}
                      disabled
                      readOnly
                      className="bg-gray-50 text-gray-500 font-mono text-sm"
                    />
                    <p className="text-xs text-gray-500 mt-1.5">Derived securely from the business name.</p>
                  </div>
                  
                  <Input
                    label="Portal Username"
                    value="Auto-generated upon creation"
                    disabled
                    readOnly
                    className="bg-gray-50 text-gray-500 font-mono text-sm italic"
                  />
                </div>
                
                <div>
                  <Input
                    label="Portal Password"
                    type="password"
                    value="****************"
                    disabled
                    readOnly
                    className="bg-gray-50 text-gray-500"
                  />
                  <p className="text-xs text-gray-500 mt-1.5">Securely generated by the backend cryptography engine. Never logged.</p>
                </div>
              </div>

              <div className="pt-6 flex justify-end gap-3 border-t border-gray-100">
                <Button
                  type="button"
                  variant="secondary"
                  onClick={() => router.push('/tabdeal/clients')}
                  disabled={isSubmitting}
                >
                  Cancel
                </Button>
                <Button
                  type="submit"
                  variant="primary"
                  isLoading={isSubmitting}
                  disabled={!formData.businessName || !formData.categoryId || isSubmitting}
                >
                  Provision Client Tenant
                </Button>
              </div>
            </form>
          </Card>
        </div>
        
        <div className="lg:col-span-1">
          <Card className="p-5 bg-indigo-50/50 border-indigo-100">
            <h4 className="font-semibold text-indigo-900 mb-3 flex items-center gap-2">
              <Building className="w-4 h-4" /> Provisioning Flow
            </h4>
            <ul className="space-y-3 text-sm text-indigo-800/80">
              <li className="flex items-start gap-2">
                <div className="w-5 h-5 rounded-full bg-indigo-200 text-indigo-700 flex items-center justify-center shrink-0 font-bold text-xs mt-0.5">1</div>
                <span>Creates isolated tenant environment.</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-5 h-5 rounded-full bg-indigo-200 text-indigo-700 flex items-center justify-center shrink-0 font-bold text-xs mt-0.5">2</div>
                <span>Generates secure portal credentials.</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-5 h-5 rounded-full bg-indigo-200 text-indigo-700 flex items-center justify-center shrink-0 font-bold text-xs mt-0.5">3</div>
                <span>Provisions category-specific Master Templates.</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-5 h-5 rounded-full bg-indigo-200 text-indigo-700 flex items-center justify-center shrink-0 font-bold text-xs mt-0.5">4</div>
                <span>Initializes dedicated WhatsApp Baileys session container.</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-5 h-5 rounded-full bg-indigo-200 text-indigo-700 flex items-center justify-center shrink-0 font-bold text-xs mt-0.5">5</div>
                <span>Generates root telemetry API Key.</span>
              </li>
            </ul>
          </Card>
        </div>
      </div>
    </div>
  );
}

function CredentialHandover({ successData, setSuccessData }: { successData: any, setSuccessData: (d: any) => void }) {
  const router = useRouter();
  
  const [showPassword, setShowPassword] = useState(false);
  const [showApiKey, setShowApiKey] = useState(false);
  
  const [copiedField, setCopiedField] = useState<string | null>(null);

  const handleCopy = (text: string, field: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(field);
    setTimeout(() => setCopiedField(null), 2000);
  };

  const handleCopyAll = () => {
    const text = `Blastup Client Credentials

Business:
${successData.businessName}

Client ID:
${successData.clientId || successData._id}

Portal Username:
${successData.username}

Portal Password:
${successData.password}

API Key:
${successData.apiKey}`;

    navigator.clipboard.writeText(text);
    setCopiedField('all');
    setTimeout(() => setCopiedField(null), 2000);
  };

  return (
    <div className="max-w-3xl mx-auto animate-in fade-in zoom-in-95 duration-500">
      <PageHeader 
        title="Client Created Successfully" 
        description="The tenant workspace and templates have been successfully provisioned." 
      />

      <div className="p-4 mb-6 bg-amber-50 border border-amber-200 rounded-lg flex items-start gap-3">
        <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
        <div>
          <h3 className="text-sm font-bold text-amber-800">Critical Security Notice</h3>
          <p className="text-sm text-amber-700 mt-1 leading-relaxed">
            These credentials are shown only once. Save them securely before leaving this page. The API key is stored securely as a hash and cannot be retrieved later.
          </p>
        </div>
      </div>

      <Card className="divide-y divide-gray-100 overflow-hidden shadow-md">
        
        {/* Business Header */}
        <div className="p-6 bg-gray-50/50">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Business</p>
              <h2 className="text-2xl font-bold text-gray-900">{successData.businessName}</h2>
              <p className="text-sm text-gray-500 mt-1 font-mono">Slug: {successData.slug} | ID: {successData.clientId || successData._id}</p>
            </div>
            <div className="text-right">
              <div className="text-sm text-gray-600">Templates Provisioned: <span className="font-semibold text-gray-900">{successData.templatesProvisioned || 0}</span></div>
              <div className="text-sm text-gray-600">WhatsApp Account: <span className="font-semibold text-gray-900">{successData.whatsappProvisioned ? 'Provisioned (Disconnected / Pending)' : 'Not Provisioned'}</span></div>
            </div>
          </div>
        </div>

        {/* Portal Login */}
        <div className="p-6">
          <h3 className="text-base font-bold text-gray-900 mb-4 flex items-center gap-2">
            <ShieldCheck className="w-5 h-5 text-indigo-500" /> Portal Login
          </h3>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-1">
              <label className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Username</label>
              <div className="flex items-center gap-2">
                <code className="flex-1 block px-3 py-2 bg-gray-50 border border-gray-200 rounded-md text-sm font-mono text-gray-900">
                  {successData.username}
                </code>
                <Button type="button" variant="outline" onClick={() => handleCopy(successData.username, 'username')} className="shrink-0 px-3">
                  {copiedField === 'username' ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4 text-gray-500" />}
                </Button>
              </div>
            </div>
            
            <div className="space-y-1">
              <label className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Password</label>
              <div className="flex items-center gap-2">
                <code className="flex-1 block px-3 py-2 bg-gray-50 border border-gray-200 rounded-md text-sm font-mono text-gray-900 tracking-wider">
                  {showPassword ? successData.password : '••••••••••••••••'}
                </code>
                <Button type="button" variant="outline" onClick={() => setShowPassword(!showPassword)} className="shrink-0 px-3">
                  {showPassword ? <EyeOff className="w-4 h-4 text-gray-500" /> : <Eye className="w-4 h-4 text-gray-500" />}
                </Button>
                <Button type="button" variant="outline" onClick={() => handleCopy(successData.password, 'password')} className="shrink-0 px-3">
                  {copiedField === 'password' ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4 text-gray-500" />}
                </Button>
              </div>
              <p className="text-xs text-gray-500 pt-1">Save this password securely. It will not be displayed again.</p>
            </div>
          </div>
        </div>

        {/* API Integration */}
        <div className="p-6 bg-indigo-50/20">
          <h3 className="text-base font-bold text-gray-900 mb-4 flex items-center gap-2">
            <Building className="w-5 h-5 text-indigo-500" /> System Integration
          </h3>
          
          <div className="space-y-1">
            <label className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Root API Key</label>
            <div className="flex items-center gap-2 max-w-2xl">
              <code className="flex-1 block px-3 py-2 bg-white border border-gray-300 rounded-md text-sm font-mono text-gray-900 break-all">
                {showApiKey ? successData.apiKey : `${successData.apiKey.substring(0, 11)}${'•'.repeat(24)}`}
              </code>
              <Button type="button" variant="outline" onClick={() => setShowApiKey(!showApiKey)} className="shrink-0 px-3 bg-white">
                {showApiKey ? <EyeOff className="w-4 h-4 text-gray-500" /> : <Eye className="w-4 h-4 text-gray-500" />}
              </Button>
              <Button type="button" variant="outline" onClick={() => handleCopy(successData.apiKey, 'apikey')} className="shrink-0 px-3 bg-white">
                {copiedField === 'apikey' ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4 text-gray-500" />}
              </Button>
            </div>
            <p className="text-xs text-gray-500 pt-1">
              Keep this API key secret. It is used by the client's website/backend to authenticate notification requests.
            </p>
          </div>
        </div>
        
        <div className="p-4 bg-gray-50 border-t border-gray-100 flex justify-between items-center">
          <Button type="button" variant="outline" onClick={handleCopyAll} className="bg-white">
            {copiedField === 'all' ? (
              <><Check className="w-4 h-4 mr-2 text-emerald-600" /> Copied All Credentials</>
            ) : (
              <><Copy className="w-4 h-4 mr-2 text-gray-500" /> Copy All Credentials</>
            )}
          </Button>
        </div>
      </Card>

      <div className="pt-6 flex justify-between items-center">
        <Button
          type="button"
          variant="secondary"
          onClick={() => setSuccessData(null)}
        >
          Create Another Client
        </Button>
        <Button
          type="button"
          variant="primary"
          onClick={() => router.push(`/tabdeal/clients/${successData.clientId || successData._id}`)}
        >
          Open Client 360
        </Button>
      </div>
    </div>
  );
}
