'use client';

import { useState, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import useSWR from 'swr';
import { PageHeader } from '@/components/layout/PageHeader';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { ErrorState } from '@/components/ui/States';
import { tabdealApi, ApiError } from '@/lib/api';
import { Building, ShieldCheck, HelpCircle } from 'lucide-react';
import toast from 'react-hot-toast';

export default function CreateClientPage() {
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);

  const [formData, setFormData] = useState({
    businessName: '',
    categoryId: '',
    email: '',
    whatsappNumber: '',
  });

  const { data: categoriesData, isLoading: loadingCategories } = useSWR(
    '/api/tabdeal/categories',
    tabdealApi.getCategories
  );

  // Derived auto-generated fields for UI feedback (matching backend logic)
  const autoGeneratedSlug = useMemo(() => {
    return formData.businessName
      ? formData.businessName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
      : 'auto-generated-slug';
  }, [formData.businessName]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);

    if (!formData.businessName.trim() || !formData.categoryId) {
      setFormError('Business name and category are required.');
      return;
    }

    setIsSubmitting(true);
    try {
      // Backend automatically provisions templates based on category.defaultTemplatePackId
      // and securely generates a unique username and password.
      const res = await tabdealApi.createClient({
        businessName: formData.businessName,
        categoryId: formData.categoryId,
        email: formData.email || undefined,
        whatsappNumber: formData.whatsappNumber || undefined,
      });

      toast.success('Client created successfully');
      router.push(`/tabdeal/clients/${res.data.clientId || res.data._id}`);
    } catch (err: any) {
      if (err instanceof ApiError) {
        setFormError(err.message || 'Failed to create client');
      } else {
        setFormError('An unexpected server error occurred.');
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  const categories = categoriesData?.data?.filter((c: any) => c.active) || [];

  return (
    <div className="max-w-4xl mx-auto animate-in fade-in duration-500 space-y-6">
      <PageHeader 
        title="Create Client" 
        description="Provision a new isolated client tenant. The system will automatically provision their templates and WhatsApp instance." 
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2">
          <Card className="p-6">
            <form onSubmit={handleSubmit} className="space-y-6">
              
              {formError && (
                <div className="p-4 bg-rose-50 border border-rose-200 rounded-lg flex items-start gap-3 text-rose-800">
                  <HelpCircle className="w-5 h-5 shrink-0 mt-0.5" />
                  <span className="text-sm font-medium">{formError}</span>
                </div>
              )}

              <div className="space-y-4">
                <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider border-b border-gray-100 pb-2">
                  Business Information
                </h3>
                
                <div>
                  <Input
                    label="Business Name"
                    placeholder="e.g. Divine Tours"
                    value={formData.businessName}
                    onChange={(e) => setFormData(f => ({ ...f, businessName: e.target.value }))}
                    required
                    maxLength={150}
                  />
                  <p className="text-xs text-gray-500 mt-1.5">The official name of the client.</p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">
                    Business Category
                  </label>
                  <select
                    className="block w-full rounded-lg border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm bg-white py-2.5 px-3"
                    value={formData.categoryId}
                    onChange={(e) => setFormData(f => ({ ...f, categoryId: e.target.value }))}
                    required
                    disabled={loadingCategories}
                  >
                    <option value="" disabled>Select a category...</option>
                    {categories.map((c: any) => (
                      <option key={c._id} value={c._id}>
                        {c.name} {c.defaultTemplatePackId ? '' : '(No default template pack)'}
                      </option>
                    ))}
                  </select>
                  {loadingCategories ? (
                    <p className="text-xs text-gray-500 mt-1.5 animate-pulse">Loading active categories...</p>
                  ) : (
                    <p className="text-xs text-gray-500 mt-1.5">
                      Determines the default master templates provisioned for this client.
                    </p>
                  )}
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
                  <Input
                    label="Contact Email (Optional)"
                    type="email"
                    placeholder="contact@business.com"
                    value={formData.email}
                    onChange={(e) => setFormData(f => ({ ...f, email: e.target.value }))}
                  />
                  
                  <div>
                    <Input
                      label="WhatsApp Number (Optional)"
                      placeholder="e.g. 919876543210"
                      value={formData.whatsappNumber}
                      onChange={(e) => setFormData(f => ({ ...f, whatsappNumber: e.target.value }))}
                    />
                    <p className="text-xs text-gray-500 mt-1.5">Include country code without plus sign.</p>
                  </div>
                </div>
              </div>

              <div className="space-y-4 pt-4">
                <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider border-b border-gray-100 pb-2 flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-indigo-500" /> System Identity (Auto-Generated)
                </h3>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <Input
                      label="Client Slug"
                      value={autoGeneratedSlug}
                      disabled
                      readOnly
                      className="bg-gray-50 text-gray-500 font-mono text-sm"
                    />
                    <p className="text-xs text-gray-500 mt-1.5">Derived securely from the business name.</p>
                  </div>
                  
                  <Input
                    label="Portal Username"
                    value="Auto-generated upon creation"
                    disabled
                    readOnly
                    className="bg-gray-50 text-gray-500 font-mono text-sm italic"
                  />
                </div>
                
                <div>
                  <Input
                    label="Portal Password"
                    type="password"
                    value="****************"
                    disabled
                    readOnly
                    className="bg-gray-50 text-gray-500"
                  />
                  <p className="text-xs text-gray-500 mt-1.5">Securely generated by the backend cryptography engine. Never logged.</p>
                </div>
              </div>

              <div className="pt-6 flex justify-end gap-3 border-t border-gray-100">
                <Button
                  type="button"
                  variant="secondary"
                  onClick={() => router.push('/tabdeal/clients')}
                  disabled={isSubmitting}
                >
                  Cancel
                </Button>
                <Button
                  type="submit"
                  variant="primary"
                  isLoading={isSubmitting}
                  disabled={!formData.businessName || !formData.categoryId || isSubmitting}
                >
                  Provision Client Tenant
                </Button>
              </div>
            </form>
          </Card>
        </div>
        
        <div className="lg:col-span-1">
          <Card className="p-5 bg-indigo-50/50 border-indigo-100">
            <h4 className="font-semibold text-indigo-900 mb-3 flex items-center gap-2">
              <Building className="w-4 h-4" /> Provisioning Flow
            </h4>
            <ul className="space-y-3 text-sm text-indigo-800/80">
              <li className="flex items-start gap-2">
                <div className="w-5 h-5 rounded-full bg-indigo-200 text-indigo-700 flex items-center justify-center shrink-0 font-bold text-xs mt-0.5">1</div>
                <span>Creates isolated tenant environment.</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-5 h-5 rounded-full bg-indigo-200 text-indigo-700 flex items-center justify-center shrink-0 font-bold text-xs mt-0.5">2</div>
                <span>Generates secure portal credentials.</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-5 h-5 rounded-full bg-indigo-200 text-indigo-700 flex items-center justify-center shrink-0 font-bold text-xs mt-0.5">3</div>
                <span>Provisions category-specific Master Templates.</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-5 h-5 rounded-full bg-indigo-200 text-indigo-700 flex items-center justify-center shrink-0 font-bold text-xs mt-0.5">4</div>
                <span>Initializes dedicated WhatsApp Baileys session container.</span>
              </li>
              <li className="flex items-start gap-2">
                <div className="w-5 h-5 rounded-full bg-indigo-200 text-indigo-700 flex items-center justify-center shrink-0 font-bold text-xs mt-0.5">5</div>
                <span>Generates root telemetry API Key.</span>
              </li>
            </ul>
          </Card>
        </div>
      </div>
    </div>
  );
}
